openapi: 3.1.0
info:
  title: Habitica Proxy API
  description: OpenAPI specification for interacting with the Habitica API via a proxy server.
  version: v1.0.0
servers:
  - url: https://habitica-proxy-misty-sun-5caa.jeffreyfazal.workers.dev/
paths:
  /tasks/user:
    get:
      operationId: getUserTasks
      summary: Get a user's tasks
      description: Retrieve a list of tasks for the authenticated user. Tasks can be filtered by type.
      security:
        - XAuthKey: []  # Apply security scheme
      parameters:
        - name: type
          in: query
          description: Filter tasks by type.
          required: false
          schema:
            type: string
            enum: [habits, dailies, todos, rewards, completedTodos]
      responses:
        '200':
          description: A list of user tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing X-Auth-Key
components:
  securitySchemes:
    XAuthKey:
      type: apiKey
      in: header
      name: X-Auth-Key
      description: API key for authenticating requests.
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the task.
        text:
          type: string
          description: The title or description of the task.
        type:
          type: string
          enum: [habits, dailies, todos, rewards, completedTodos]
          description: The type of task.